window.UNCUT_SITE_CONFIG = {
  brandName: "Uncut_Lesson",
  homeHeroEyebrow: "Digital Learning Courses",
  homeHeroTitle: "Online Education Feels Like Real Classroom",
  homeHeroText: "Build skills with focused online programs, live support, and practical learning paths designed to move you forward.",
  homeHeroPrimaryText: "Explore Courses",
  homeHeroPrimaryUrl: "courses.html",
  homeHeroSecondaryText: "Watch Free Videos",
  homeHeroSecondaryUrl: "free-video.html",
  heroImages: [
    "assets/Offer.jpg",
    "assets/Student-Index.jpg",
    "assets/Student-Courses.jpg",
    "assets/Power BI.jpg",
    "assets/Tally Prime.jpg",
    "assets/Advance Excel.jpg"
  ],
  paymentQrImage: "assets/payment-qr.jpeg",
  upiId: "alokmistri69-2@oksbi",
  whatsappNumber: "917439034248",
  paymentHelpText: "Submit payment details after payment.",
  supportEmail: "uncutlesson@gmail.com",
  supportWhatsapp: "917439034248",
  appsScriptEndpoint: "https://script.google.com/macros/s/AKfycbwtIBMIzUCad-KGrhOF63c6qfMiYB5z-YpQc9gFaMrrQ7_aHlWxZszeF_1anwXd0K96Eg/exec",
  catalogSyncEnabled: true,
  supportHeroTitle: "We Are Here To Help You Quickly And Clearly",
  supportHeroText: "If you need course guidance, account help, or general information, you can contact us directly using email or WhatsApp.",
  primaryColor: "#1f6fff",
  accentColor: "#ffb200",
  textColor: "#16325c",
  fontStyle: "Manrope",
  sliderStyle: "fade",
  sliderSpeedMs: 3500,
  adEnabled: true,
  adDelayMs: 60000,
  adEyebrow: "Featured Offer",
  adTitle: "New Season Offer For Smart Learners",
  adText: "Join our best-selling classes with guided lessons, practical training, and direct support in one place.",
  adPrimaryText: "Start Learning",
  adPrimaryUrl: "payment.html?course=Uncut%20Lesson%20Featured%20Offer&price=Selected%20on%20confirmation",
  adSecondaryText: "View Courses",
  adSecondaryUrl: "courses.html",
  adImage: "assets/Offer.jpg"
};
