const drivePlaceholder = "#";

const courses = {
  "ms-basic": {
    label: "MS-Basic",
    title: "MS Word Learning Section",
    description: "Complete MS Word lessons from introduction to track changes and markup.",
    image: "../assets/Basic.jpg",
    price: "Rs 99",
    payment: "../payment.html?course=Basic%20Course&price=Rs%20499",
    topics: [
      ["MS Word Introduction", "Drive Video", "https://drive.google.com/file/d/1L4ShChbuUVQs4GeyuljljJ5tkuCgTT6V/view?usp=drive_link"],
      ["MS Word Font Formatting", "Drive Video", "https://drive.google.com/file/d/1bSJNmELwnkWWsQqzcJlTbPTcbuHJiSyF/view?usp=drive_link"],
      ["Paragraph Options", "Drive Video", "https://drive.google.com/file/d/1oVtzKcN0zpBhQYcR-xzQ9rly_jL-C76I/view?usp=drive_link"],
      ["Bullets And Numbering", "Drive Video", "https://drive.google.com/file/d/1nNnc9HEpDrF8NOMF-13v9HGcOugQ-wiy/view?usp=drive_link"],
      ["Sorting Option", "Drive Video", "https://drive.google.com/file/d/1a1K0uyq-b85Q64uS64oBi-RapdbQ2EXm/view?usp=drive_link"],
      ["Styles In Word - Heading Pattern", "Drive Video", "https://drive.google.com/file/d/1-KWCKKe6xsr2As0bkKuFf47O-zoa-3Ga/view?usp=drive_link"],
      ["Collapse And Expand Section In Word", "Drive Video", "https://drive.google.com/file/d/1uDViku2Lsexi24fyx7GwWjoIHWIolY_f/view?usp=drive_link"],
      ["Page, Cover Page, Page Break", "Drive Video", "https://drive.google.com/file/d/1cBHlkMnErQBxUPVMIu0-81MIr3bJpS2M/view?usp=drive_link"],
      ["Creating Table In Word", "Drive Video", "https://drive.google.com/file/d/1Wru9Tvpoi3luWA49ckrLlxtw_n3E4svt/view?usp=drive_link"],
      ["Pictures In MS Word", "Drive Video", "https://drive.google.com/file/d/15jneht5KJfzOYED6bdXgFE3xvwEsHnyU/view?usp=drive_link"],
      ["Picture And Live Layout In Word", "Drive Video", "https://drive.google.com/file/d/1b9JnyLt8Lr2wGeQleNvmfQSI6MZw7iE_/view?usp=drive_link"],
      ["Shapes In MS Word", "Drive Video", "https://drive.google.com/file/d/1N6bYO4HdxnSyLZIceIMO2qVtf5Ex6w5B/view?usp=drive_link"],
      ["SmartArt In MS Word - Create Hierarchy Structure", "Drive Video", "https://drive.google.com/file/d/1KwzU4NbyFP7FcvX9iniLdSYV4OtGnF0Q/view?usp=drive_link"],
      ["Chart And Screenshot", "Drive Video", "https://drive.google.com/file/d/10h809UHl382etSjmaMCgSTecFcKaKK7q/view?usp=drive_link"],
      ["Bookmark And Cross Reference", "Drive Video", "https://drive.google.com/file/d/13Rifq5nDNcUm9NrsdChsBSyD5bW7523C/view?usp=drive_link"],
      ["Hyperlink In Word", "Drive Video", "https://drive.google.com/file/d/1gDsRtWCd-uZC52yItPZhqhT7kDoAN9V4/view?usp=drive_link"],
      ["Header And Footer And Page No", "Drive Video", "https://drive.google.com/file/d/1pqwOL2eb3zdCh1CS7qua8LmOjJ82x-L3/view?usp=drive_link"],
      ["Text Box, WordArt, Drop Cap And Symbols", "Drive Video", "https://drive.google.com/file/d/1ZRSuO5r6pt4Nz4pflcmikUkbCwLyfuws/view?usp=drive_link"],
      ["Quick Parts In MS Word", "Drive Video", "https://drive.google.com/file/d/1jBe_pxXTYR8RbxBChTFvQQicLGVX0bBc/view?usp=drive_link"],
      ["Print Related Option", "Drive Video", "https://drive.google.com/file/d/1dsy1Bro4ejtMwk7k1HyQL5qkl0kEkd0F/view?usp=drive_link"],
      ["Page Color And Page Border", "Drive Video", "https://drive.google.com/file/d/1qSlpYgLc7plVxp8pMI5wFgOwnFQXj1Bs/view?usp=drive_link"],
      ["Read Aloud And Immersive Reader", "Drive Video", "https://drive.google.com/file/d/1fZKeSPHIwYkchxwR1CTw9NzAf-wBtHVW/view?usp=drive_link"],
      ["Table Of Content", "Drive Video", "https://drive.google.com/file/d/1Wr_afV-hGj1NF7qqwmS6tP9beJREPBSm/view?usp=drive_link"],
      ["Bibliography And Citation", "Drive Video", "https://drive.google.com/file/d/1-oX1-siM4p5sFOqmHKcL5EL-dIFVuKWd/view?usp=drive_link"],
      ["Caption In MS Word", "Drive Video", "https://drive.google.com/file/d/1ixFEC0sr7BNNfV0cf-26tHy-3ptyIY4S/view?usp=drive_link"],
      ["Footnote And Endnote", "Drive Video", "https://drive.google.com/file/d/1cglEohDk8142p8bgP-RbNIU2vyJP-rLb/view?usp=drive_link"],
      ["Watermark In MS Word", "Drive Video", "https://drive.google.com/file/d/1LroyR2Ua2lpfNj4JRzsf9v_BSTZJ5QIl/view?usp=drive_link"],
      ["Mark Entry In MS Word", "Drive Video", "https://drive.google.com/file/d/1hCix3dwLvrzSPDjwlqK9mj4Pcsx6oD2S/view?usp=drive_link"],
      ["Mail Merge", "Drive Video", "https://drive.google.com/file/d/1vD2LItYNhDrpmhKbSY2XKH5sedLIHyYM/view?usp=drive_link"],
      ["Language And Proof", "Drive Video", "https://drive.google.com/file/d/1fNbqvEO6H4rJVnPIopnW5ORsvlYoTvi0/view?usp=drive_link"],
      ["Track Changes In Word", "Drive Video", "https://drive.google.com/file/d/1BgrVKHdXnMhDYOfm6VCgKkIA0N6EarM2/view?usp=drive_link"],
      ["Simple Markup In MS Word", "Drive Video", "https://drive.google.com/file/d/1fNV2Jm7osYiMyRhNLK5ue5L95xaHINar/view?usp=drive_link"],
      ["Full Powerpoint Course", "Drive Video", "https://drive.google.com/drive/folders/1PmK45FOgsrjUTA8b7OZYDyU30QC0nFmY?usp=drive_link"],
    ],
  },
  "advanced-excel": {
    label: "Advanced Excel",
    title: "Advanced Excel Learning Section",
    description: "Advanced formulas, lookup, pivot tables, charts, reporting, and data handling.",
    image: "../assets/Advance Excel.jpg",
    price: "Rs 299",
    payment: "../payment.html?course=Advanced%20Excel%20%2B%20MS-Access&price=Rs%20999",
    topics: [
      ["Excel structure..", "Drive Video", "https://drive.google.com/file/d/1NN66Nl2uzm4u1aCG0UH2XqNGLEK883IT/view?usp=drive_link"],
      ["Cell properties..", "Drive Video", "https://drive.google.com/file/d/1J0AgI3xOwKL64JHe281w28JEYiAgpm49/view?usp=drive_link"],
      ["Autofill value and text..", "Drive Video", "https://drive.google.com/file/d/13sT7D4Yidy-PYmM_V71YWM3ZinBYgT9D/view?usp=drive_link"],
      ["Autofill date..", "Drive Video", "https://drive.google.com/file/d/1_e1TDArU-Q5AMuLLx4OingHTi1n1ZKng/view?usp=drive_link"],
      ["Autofill Adv tools..", "Drive Video", "https://drive.google.com/file/d/122Wwne4moSorC_z_hr0fqeV9i4Qg6wAN/view?usp=drive_link"],
      ["Flash Fill in Excel - Updated..", "Drive Video", "https://drive.google.com/file/d/1iHOLeOdxd-4zrZISbsKqx80UnoXmDcU4/view?usp=drive_link"],
      ["Cell reference..", "Drive Video", "https://drive.google.com/file/d/1x_rC5n9y8ypyXSfYK8DwS139dNBqxF2z/view?usp=drive_link"],
      ["Operators based Equation..", "Drive Video", "https://drive.google.com/file/d/1x_rC5n9y8ypyXSfYK8DwS139dNBqxF2z/view?usp=drive_link"],
      ["Math Function..", "Drive Video", "https://drive.google.com/file/d/1fnO5D3dZrvpU1iuIkkcu_4kbSd6VIo8Q/view?usp=drive_link"],
      ["Text Function - Upper, Lower, Proper, Trim..", "Drive Video", "https://drive.google.com/file/d/1xbvFavNoN4qCy6iGZEar0N6rR8JPy8Fx/view?usp=drive_link"],
      ["Text Function - Right, Left..", "Drive Video", "https://drive.google.com/file/d/1zlqRj0wvTAOAYTb3yqaGcwPj8UZHJIhY/view?usp=drive_link"],
      ["Text Function - Find and task..", "Drive Video", "https://drive.google.com/file/d/1KPE2ZcDWa1UDdXCOk8QQMHu_aiBdPW93/view?usp=drive_link"],
      ["Text Function - Solution and Nested Left..", "Drive Video", "https://drive.google.com/file/d/1qOKHExvc7IGb4pSvaRe2i-1NM6Qou4N1/view?usp=drive_link"],
      ["Text Function - Find and Left Nesting..", "Drive Video", "https://drive.google.com/file/d/1aQte-3eAS5hkEVARrK1WR040tiGINqjE/view?usp=drive_link"],
      ["Text Function - MID", "Drive Video", "https://drive.google.com/file/d/1F4i9TT3N_FcHvZBn1iCB6cLv2VWYDd1I/view?usp=drive_link"],
      ["Text Function - Mid task and solution", "Drive Video", "https://drive.google.com/file/d/1bwJnPS8mD6txufCROHSkftNCyHVdW8yo/view?usp=drive_link"],
      ["Text Function - Concatenate", "Drive Video", "https://drive.google.com/file/d/18wlq1fm_svxLYmyx9MUE8ruPhmMVPog3/view?usp=drive_link"],
      ["Text Function - Concatenate task and solution", "Drive Video", "https://drive.google.com/file/d/1owNO9J0iGnD1453iTCg2TlGr8728P8JX/view?usp=drive_link"],
      ["Concat and Textjoin Function - Updated", "Drive Video", "https://drive.google.com/file/d/15JXSVxUhZ2UHXjwO9FkROhGEGf83VTBl/view?usp=drive_link"],
      ["Text Function - Replace", "Drive Video", "https://drive.google.com/file/d/1r_kI2ZfMeOQUC6APNGckUwghnHvr7HBt/view?usp=drive_link"],
      ["Text Function - Replace task and Solution", "Drive Video", "https://drive.google.com/file/d/1cE1nW4F2w7iyzqhD8pGF5CU4NX2VvH4V/view?usp=drive_link"],
      ["Text Function - Substitute", "Drive Video", "https://drive.google.com/file/d/1IvuhGxOZrZtVJJumH_dI3QaVernnUsln/view?usp=drive_link"],
      ["Text Function - Len, Rept, Exact, Search", "Drive Video", "https://drive.google.com/file/d/1bg9mT65bMqI-CYHA7UvCX42svzrIxO_s/view?usp=drive_link"],
      ["Numbervalue Function in Excel - Updated", "Drive Video", "https://drive.google.com/file/d/12iFpBEIWlO5NJXENpjfM99Czw6k5VG_u/view?usp=drive_link"],
      ["Text to Column", "Drive Video", "https://drive.google.com/file/d/1qMeDEx0nbzIxllPnCf6sWYm2Yt64NxMM/view?usp=drive_link"],
      ["Workbook protect", "Drive Video", "https://drive.google.com/file/d/1ealc8TDV0wSo9QkGVWbmi6MULh-Ns8zP/view?usp=drive_link"],
      ["Protect sheet", "Drive Video", "https://drive.google.com/file/d/1vYT3VXKBM16q_6i7-pEqYVRNlmaBOKg3/view?usp=drive_link"],
      ["Hide Formulas and unlocked Cell", "Drive Video", "https://drive.google.com/file/d/16sREHUh4kL0EVvD64RUG4vb2HJFLasWp/view?usp=drive_link"],
      ["Protect File with password", "Drive Video", "https://drive.google.com/file/d/1CbYAm8UNSgSV2WH1KRYZC7qwG9ssem1E/view?usp=drive_link"],
      ["If Function - Logical Test", "Drive Video", "https://drive.google.com/file/d/1l9zYMqRsmdTMz3GoIrfAORni_mys2n5p/view?usp=drive_link"],
      ["If Function - with Equation and task", "Drive Video", "https://drive.google.com/file/d/1mDwtQ7VD0WsQRleAH6gVhQuFtvQXccct/view?usp=drive_link"],
      ["If Function - Nested If", "Drive Video", "https://drive.google.com/file/d/1FlMcXi45PJ8abTHXAStGqOspN3qU34Fc/view?usp=drive_link"],
      ["IFS in Excel - Updated", "Drive Video", "https://drive.google.com/file/d/15nuK9atDn7-7FgQkJS-i1zJjwEaEhaUG/view?usp=drive_link"],
      ["If Function - advance", "Drive Video", "https://drive.google.com/file/d/1IvcrH7tzYIVpj9oiMnZAvi4phAP1Q2Ro/view?usp=drive_link"],
      ["If Function - adv 2", "Drive Video", "https://drive.google.com/file/d/1tPYCr5m73UxMs7axphEiVlbzc8F4NWsg/view?usp=drive_link"],
      ["AND, OR Function", "Drive Video", "https://drive.google.com/file/d/1Ygj8sQite74wjoAAheAP-P-AnZNcWNEd/view?usp=drive_link"],
      ["AND, OR, IF Nested", "Drive Video", "https://drive.google.com/file/d/1k2Q-pwq5fkX0LkN6z2YFQhAbzhsGqePp/view?usp=drive_link"],
      ["AND, OR Advance", "Drive Video", "https://drive.google.com/file/d/1f7XOjtuDP1ipuVAAdsxZDde4pF7ga6eq/view?usp=drive_link"],
      ["XOR Function - Updated", "Drive Video", "https://drive.google.com/file/d/1lQ6kdGmMdaGlnsaxzW6JVsd4j2BvDVfB/view?usp=drive_link"],
      ["Pivot Table - Intro", "Drive Video", "https://drive.google.com/file/d/1otBaFAjQWMGnpj8hMs1gzXcYQff8TlTt/view?usp=drive_link"],
      ["Pivot Table - Manage Field Area", "Drive Video", "https://drive.google.com/file/d/14wrM7HcJFAntMXOtzBir2HfY_bzCo9Ut/view?usp=drive_link"],
      ["Pivot Table - Value Field, Report and more", "Drive Video", "https://drive.google.com/file/d/1SW3JrbnUOsa__LMROoz5JGMRtArncDC-/view?usp=drive_link"],
      ["Pivot Table - Slicer and Duplicate Pivot", "Drive Video", "https://drive.google.com/file/d/1YSpRLrBeBB1Q6AnKQKgWAG7FunAEy6g_/view?usp=drive_link"],
      ["Pivot Table - Group to manage date and values", "Drive Video", "https://drive.google.com/file/d/1_wx-CxXM6jw9JDS7-_33n3brsQG8e0g5/view?usp=drive_link"],
      ["Pivot Table - Insert Calculated Field", "Drive Video", "https://drive.google.com/file/d/1Gk_bwG6rAhvPgLhJgxuVQftgvw3zp_Wo/view?usp=drive_link"],
      ["Power Pivot in Excel - Updated", "Drive Video", "https://drive.google.com/file/d/1rBSj6HNselGoyAGlPQXXZjtHO69jkVbU/view?usp=drive_link"],
      ["Goal seek", "Drive Video", "https://drive.google.com/file/d/1a-_rxppM6WzcO2WrSXq1YGRWawvYuKvN/view?usp=drive_link"],
      ["Scenario manager", "Drive Video", "https://drive.google.com/file/d/1SJNSCP9GG-pKO3MkmBLCGBC70_2f_bHv/view?usp=drive_link"],
      ["PMT function - EMI calculator", "Drive Video", "https://drive.google.com/file/d/1nnM9L-czjoP_psT3hli-EH8apLi482W1/view?usp=drive_link"],
      ["Data table - Create Loan Table", "Drive Video", "https://drive.google.com/file/d/1xHCe_xhBxpPflWZ4nOQHie7gsu5X161y/view?usp=drive_link"],
      ["Pduration Function - Updated", "Drive Video", "https://drive.google.com/file/d/1KR56u3JiMqxpi_uzDz3Kl2GQrq4lBTd5/view?usp=drive_link"],
      ["Print option in Excel - Part 1", "Drive Video", "https://drive.google.com/file/d/1PQ4ionVS7eGHBoqILPXIoxpAOWXhpEy4/view?usp=drive_link"],
      ["Print option in Excel - Part 2", "Drive Video", "https://drive.google.com/file/d/1GMpp56jXnZwHvmZxfMIpmfIOiUdQUoy4/view?usp=drive_link"],
      ["Draw Tab in Excel - Updated", "Drive Video", "https://drive.google.com/file/d/1Ay2nAEZUbS3afEdFxnZcoAZv0O_cs5f_/view?usp=drive_link"],
      ["Share book", "Drive Video", "https://drive.google.com/file/d/14YADXzw0Vuv5WhMEOI6Rr1Ucs2Ro4WN3/view?usp=drive_link"],
      ["Chart Preperation", "Drive Video", "https://drive.google.com/file/d/18A_PglfkE93-IxXwCaT0ExPk-MBEEW1A/view?usp=drive_link"],
      ["Chart Preperation - Advance", "Drive Video", "https://drive.google.com/file/d/1lGD2PMt5OMKAWYoFXnm7JhRNlV0xqsuC/view?usp=drive_link"],
      ["Chart Preperation - Customize", "Drive Video", "https://drive.google.com/file/d/1VWocOBjtgoNnZCz0hHNPr8via_-vLjES/view?usp=drive_link"],
      ["Power Map in Excel - Updated", "Drive Video", "https://drive.google.com/file/d/1pAGWHqTknxb7D2tW0vTJNKtqw6Pq7K-v/view?usp=drive_link"],
      ["Quick Analysis and Chart Recommendation - Updated", "Drive Video", "https://drive.google.com/file/d/1J_q589tcRPt4dMdhNtgCAoiico04kVBc/view?usp=drive_link"],
      ["Filter option in Excel", "Drive Video", "https://drive.google.com/file/d/1B335G2EO7hMlnffJttkk_fh-k8tOMHnJ/view?usp=drive_link"],
      ["Date and Color Filter", "Drive Video", "https://drive.google.com/file/d/14dt9Toyr8tWnTzsw1nmfKeKHH1so6jKV/view?usp=drive_link"],
      ["Advanced Filter option", "Drive Video", "https://drive.google.com/file/d/1LEpvSt-HZEKBh8_2cu1UnNw098DmuljN/view?usp=drive_link"],
      ["Sorting and Custom Sort", "Drive Video", "https://drive.google.com/file/d/1bNHFQMKfI3CfH249cIljeymDQhzfS8Pv/view?usp=drive_link"],
      ["Group, Ungroup and Subtotal", "Drive Video", "https://drive.google.com/file/d/13nodjlJ32de8wghrZKkVY2U4obpVwxtD/view?usp=drive_link"],
      ["Conditional Formatting", "Drive Video", "https://drive.google.com/file/d/1Jqxwr8TdVS5_MzZvMl9T-IK0gMhT9WKB/view?usp=drive_link"],
      ["Conditional Formatting - Types of Rules", "Drive Video", "https://drive.google.com/file/d/1F85SZ2DekYQ3duiAj7mIencA0qTU9Jin/view?usp=drive_link"],
      ["Conditional Formatting - Apply", "Drive Video", "https://drive.google.com/file/d/1cf8wLWr6iXJe3dl7fC9HXLbF9xQliI5C/view?usp=drive_link"],
      ["Conditional Formatting - Create New Rules", "Drive Video", "https://drive.google.com/file/d/18939nx85FrSIe_L3diR3y0a9hfDb5Z_6/view?usp=drive_link"],
      ["Conditional Formatting - Manage Rules", "Drive Video", "https://drive.google.com/file/d/1eLkJTjxU24m5zyvKIylLs4ADyHtYTQLQ/view?usp=drive_link"],
      ["Data Validation", "Drive Video", "https://drive.google.com/file/d/1S6buXVfhkjpGzOSulOBeJGL8g1JKqty4/view?usp=drive_link"],
      ["Data Validation - Input message and Error Alert", "Drive Video", "https://drive.google.com/file/d/1Ya6SiXYNOr9ucmj9wV5G55LyqomHNjrh/view?usp=drive_link"],
      ["Advance Math Function", "Drive Video", "https://drive.google.com/file/d/1QLrC_mWpWOriRyTtyXnK7zmX8pHQ9Z7u/view?usp=drive_link"],
      ["Advance Math Function 2", "Drive Video", "https://drive.google.com/file/d/1wyw2g8ewn6yQdAnFKgu33ciIapwKClFA/view?usp=drive_link"],
      ["Using of Wild Card in Math Function", "Drive Video", "https://drive.google.com/file/d/1srpnbxXo4L35x4yV9glWbHh9XhacgphW/view?usp=drive_link"],
      ["Define Name Feature", "Drive Video", "https://drive.google.com/file/d/1amDU9iV0BxiB487J7-EeZ3e0yBs8_38e/view?usp=drive_link"],
      ["Hyperlink in Excel", "Drive Video", "https://drive.google.com/file/d/1m57zAhM7rsTE4LapNj-NDpzOIY93q5Wh/view?usp=drive_link"],
      ["VLOOKUP Function", "Drive Video", "https://drive.google.com/file/d/1NHpSoTRA_QDX7iu9fi5mIg6UDzAE5FsD/view?usp=drive_link"],
      ["VLOOKUP with IFERROR", "Drive Video", "https://drive.google.com/file/d/1AQP9n1Yzig3qgsBfuicN_CK-bVz8WFhV/view?usp=drive_link"],
      ["VLOOKUP With Nesting If", "Drive Video", "https://drive.google.com/file/d/1J5-8psq0rdixXc8vk8Gseg9TCz3EkbzE/view?usp=drive_link"],
      ["HLOOKUP", "Drive Video", "https://drive.google.com/file/d/1NHNcTUqt0HKIsUqvWwNoZ9HMuZU1Pi7Y/view?usp=drive_link"],
      ["Match Function", "Drive Video", "https://drive.google.com/file/d/1AAlR3CU59z-YKmtivRVZOEWc398WKKed/view?usp=drive_link"],
      ["INdex And Match Nested", "Drive Video", "https://drive.google.com/file/d/126x3mMwMGu-yvYOZRmRiU4XgsxU2PxML/view?usp=drive_link"],
      ["Vlookup Array", "Drive Video", "https://drive.google.com/file/d/1bh-uVFpx831YzrPwT331CgOGDMqzetoQ/view?usp=drive_link"],
      ["Vlookup Column Function Trick", "Drive Video", "https://drive.google.com/file/d/119aLfVNdlDwO0U-iLDxZw_rvOsXSM-fu/view?usp=drive_link"],
      ["VLOOKUP TRUE", "Drive Video", "https://drive.google.com/file/d/1vtYK5IW0JhxEWibo3hX-CpJJIdgCRdB9/view?usp=drive_link"],
      ["Advance VLOOKUP", "Drive Video", "https://drive.google.com/file/d/14dQcy8SsVRUORJqW_hg0JSef4J7oN2Jg/view?usp=drive_link"],
      ["Date and Time Setting", "Drive Video", "https://drive.google.com/file/d/1m8mhyAOKlYL32BW0r3icKA0-ZUQ6tFYA/view?usp=drive_link"],
      ["Date and Time Format", "Drive Video", "https://drive.google.com/file/d/1NHjkkxAinkvswbXz_2_HeNPqaBFqkNKu/view?usp=drive_link"],
      ["Date and Time Functions", "Drive Video", "https://drive.google.com/file/d/1zZx_ERxqXd6m5TbJkQ2yhf-eUxRQ58F7/view?usp=drive_link"],
      ["DATEDIF Function", "Drive Video", "https://drive.google.com/file/d/1x5PVzUu1YzUUzhWc2tqIB5a8tkHp4wqC/view?usp=drive_link"],
      ["NETWORKDAYS Function", "Drive Video", "https://drive.google.com/file/d/1zeqATF6AnQSLJMhn1JPDJ-osGzjmHTfD/view?usp=drive_link"],
      ["Macro Recording – Part 1", "Drive Video", "https://drive.google.com/file/d/1xdQmryaVzGFCfPYiDzJiyiLrsivm11U2/view?usp=drive_link"],
      ["Macro Recording – Part 2", "Drive Video", "https://drive.google.com/file/d/1H14xLlaEFAZwuDeFnFoRjnR6jDuBCbDy/view?usp=drive_link"],
      ["Macro Recording – Part 3", "Drive Video", "https://drive.google.com/file/d/1RlG-G7EMdOqmWf7MqPM4Dl7tQIkK6cDt/view?usp=drive_link"],
    ],
  },
  "tally-prime-gst": {
    label: "Tally Prime + GST",
    title: "Tally Prime + GST Learning Section",
    description: "Practical accounting, GST setup, invoice creation, reports, and business entries.",
    image: "../assets/Tally Prime.jpg",
    price: "Rs 999",
    payment: "../payment.html?course=Tally%20Prime%20%2B%20GST&price=Rs%201999",
    topics: [
      ["Tally Prime Intro", "Drive Video", "https://drive.google.com/drive/folders/1Vlgvh9x8c1mfxfiCUKWJv58u6l0mcEkV?usp=drive_link"],
      ["Installation &", "Drive Video", "https://drive.google.com/drive/folders/1B0CgmQ6Lr0lqIeIrETpK0qWVM8qf0kOf?usp=drive_link"],
      ["Company Creation", "Drive Video", "https://drive.google.com/drive/folders/1ehN-8OiQ5IfPKWhP3NHessXmUReuFQIL?usp=drive_link"],
      ["Tally Prime Screen Interface", "Drive Video", "https://drive.google.com/drive/folders/1nTEQ_QmnqnRw-FLbT95fma3osTJMnd5E?usp=drive_link"],
      ["Tally Prime Basic Accounting Transaction", "Drive Video", "https://drive.google.com/drive/folders/1B2tzNJxrgCXvTsqeXOiBlwaGMLUbOudN?usp=drive_link"],
      ["Tally Prime Business Transaction", "Drive Video", "https://drive.google.com/drive/folders/1CTXiddp7b02Z1oXJxKWWXkhQOiIidf48?usp=drive_link"],
      ["Tally Prime Basic Reports", "Drive Video", "https://drive.google.com/drive/folders/1dR6CImeL5ExRlZIYCxNlH5i56Wj8qgAt?usp=drive_link"],
      ["Tally Prime Introduction of Inventory", "Drive Video", "https://drive.google.com/drive/folders/1wnYzA2kxAW5_0QKJzGChYvQnYi8BSxPS?usp=drive_link"],
      ["GST Introduction", "Drive Video", "https://drive.google.com/drive/folders/1rvS0-2i26747Xw2vUQOFnUWo-6samMY_?usp=drive_link"],
      ["Adjustment Of ITC Liable Payment", "Drive Video", "https://drive.google.com/drive/folders/1ctgTX5CrZud8gwDvSFBR7H-jmjyAlyno?usp=drive_link"],
      ["GST Transaction", "Drive Video", "https://drive.google.com/drive/folders/1CgF-4wT1lyGQpnDJCAfjGF34Bj_8T2KI?usp=drive_link"],
      ["GST Report From Transaction", "Drive Video", "https://drive.google.com/drive/folders/1FRMv7HW_zdY1HHxEHzg7iwvC5I-J7U3_?usp=drive_link"],
      ["E-way Bill", "Drive Video", "https://drive.google.com/drive/folders/1Ycg20XdN2EkBgVjsn3Rpc3wvODRVz2hd?usp=drive_link"],
      ["Banking", "Drive Video", "https://drive.google.com/drive/folders/1F3VC_vpZD2kA43gkiJrKKHDQacYKx3yE?usp=drive_link"],
      ["Cost Centre", "Drive Video", "https://drive.google.com/drive/folders/1cqfwZJLOhp3UEL2Hyt-GHUxj110AVCJP?usp=drive_link"],
      ["Interest Calculation", "Drive Video", "https://drive.google.com/drive/folders/1-uHeEoIEq8KnOdW0R9X6QWSwFr09qoxk?usp=drive_link"],
      ["Procurement Process", "Drive Video", "https://drive.google.com/drive/folders/1VVizu3l0g0pSFE1g487x4yas1a76mJ3G?usp=drive_link"],
      ["Sales Process", "Drive Video", "https://drive.google.com/drive/folders/1Zja7yyB8UdnrkcL1ZMouxyUKL3erWHuo?usp=drive_link"],
      ["Manufacturing Process", "Drive Video", "https://drive.google.com/drive/folders/1HiPusoU7LFjorMuZ7zdKkLZ49IyQWDrU?usp=drive_link"],
      ["Item Cost Tracking & Batch Detail", "Drive Video", "https://drive.google.com/drive/folders/13zCqtTwKlBxvuhnD1tlAmfgq8-C0GEA_?usp=drive_link"],
      ["Price List", "Drive Video", "https://drive.google.com/drive/folders/1-QES7mPUlQwxJhwP7esV6LMQZ7Q1efv6?usp=drive_link"],
      ["Multi Currency", "Drive Video", "https://drive.google.com/drive/folders/1UY3u8WZGqV8_ejYkR2mhnIqsM0Nobki4?usp=drive_link"],
      ["Scheme Discount, Actual Bill & Operating Expenses", "Drive Video", "https://drive.google.com/drive/folders/1NzKbZ6EP5HwmpvE3Ztzj46sOUIWgcYrr?usp=drive_link"],
      ["Mix Supply & Detailed GST Report", "Drive Video", "https://drive.google.com/drive/folders/1MwVTKweGbCTuH5SWARHh5eX_FDCcrosB?usp=drive_link"],
      ["Payroll", "Drive Video", "https://drive.google.com/drive/folders/1qmT5Qh-iGszmntFgKE3JsTbD07OyLa66?usp=drive_link"],
      ["TDS", "Drive Video", "https://drive.google.com/drive/folders/1pP70dG9KWFXxbzUGaKWClmWkHIvkeUs0?usp=drive_link"],
      ["MIS Report", "Drive Video", "https://drive.google.com/drive/folders/1OPCaHdF4efJlERwQ8YKrMouSetoZMlKp?usp=drive_link"],
      ["Version of Tally", "Drive Video", "https://drive.google.com/drive/folders/1rTHux4SbAP9NVayme3UUZ8zu0sLDZLI2?usp=drive_link"],
      ["Career Guideline", "Drive Video", "https://drive.google.com/drive/folders/1iNTubDw1p2itYeiczbvJoyYH8Ap1pRHq?usp=drive_link"],
      ["Course Summary", "Drive Video", "https://drive.google.com/drive/folders/1Ga1ZoC-HVXlUoP4NxxDveOzSU8v99NN-?usp=drive_link"],
    ],
  },
  "tally-erp": {
    label: "Tally ERP",
    title: "Tally ERP Learning Section",
    description: "Voucher entry, inventory, accounting reports, and daily business workflow.",
    image: "../assets/Tally ERP.jpg",
    price: "Rs 999",
    payment: "../payment.html?course=Tally%20ERP&price=Rs%201499",
    topics: [
      ["Tally ERP Introduction", "15 min"],
      ["Voucher Entry", "33 min"],
      ["Inventory Management", "28 min"],
      ["Accounting Reports", "25 min"],
      ["Ledger And Balance Setup", "27 min"],
    ],
  },
  "power-bi": {
    label: "Power BI",
    title: "Power BI Basic To Advance Learning Section",
    description: "Power Query, DAX, data model, dashboard design, and final report creation.",
    image: "../assets/Power BI.jpg",
    price: "Rs 1499",
    payment: "../payment.html?course=Power%20BI%20A%20to%20Z&price=Rs%201999",
    topics: [
      ["The Power BI Masterclass 2022 lets get started", "Google Drive", "https://drive.google.com/drive/folders/1hIXsD6az9VZGlV7RRT-SueOY1gI5682P?usp=drive_link"],
      ["The Power BI Masterclass 2022 lets get started", "Google Drive", "https://drive.google.com/drive/folders/1hIXsD6az9VZGlV7RRT-SueOY1gI5682P?usp=drive_link"],
      ["If necessary enable the new format pane preview feature", "Google Drive", "https://drive.google.com/drive/folders/1hIXsD6az9VZGlV7RRT-SueOY1gI5682P?usp=drive_link"],
      ["A complete tour through the Power BI Interface", "Google Drive", "https://drive.google.com/drive/folders/1hIXsD6az9VZGlV7RRT-SueOY1gI5682P?usp=drive_link"],
      ["Our first Power BI Report lets get started", "Google Drive", "https://drive.google.com/drive/folders/1hIXsD6az9VZGlV7RRT-SueOY1gI5682P?usp=drive_link"],
      ["Finishing our first report", "Google Drive", "https://drive.google.com/drive/folders/1hIXsD6az9VZGlV7RRT-SueOY1gI5682P?usp=drive_link"],
      ["Power BI the more advanced way exploring the dataset", "Google Drive", "https://drive.google.com/drive/folders/1hIXsD6az9VZGlV7RRT-SueOY1gI5682P?usp=drive_link"],
      ["Preparing the dataset using Power Query Editor", "Google Drive", "https://drive.google.com/drive/folders/1hIXsD6az9VZGlV7RRT-SueOY1gI5682P?usp=drive_link"],
      ["How to create a proper Datestable in Power BI", "Google Drive", "https://drive.google.com/drive/folders/1hIXsD6az9VZGlV7RRT-SueOY1gI5682P?usp=drive_link"],
      ["Datatransformation and cleaning Lets explore the Power Query Editor", "Google Drive", "https://drive.google.com/drive/folders/1hIXsD6az9VZGlV7RRT-SueOY1gI5682P?usp=drive_link"],
      ["Data enrichment with web data extraction", "Google Drive", "https://drive.google.com/drive/folders/1hIXsD6az9VZGlV7RRT-SueOY1gI5682P?usp=drive_link"],
      ["Datamodel setup Modelview and Relationships", "Google Drive", "https://drive.google.com/drive/folders/1hIXsD6az9VZGlV7RRT-SueOY1gI5682P?usp=drive_link"],
      ["Introduction to calculated columns and measures in Power BI", "Google Drive", "https://drive.google.com/drive/folders/1hIXsD6az9VZGlV7RRT-SueOY1gI5682P?usp=drive_link"],
      ["The measures table trick", "Google Drive", "https://drive.google.com/drive/folders/1hIXsD6az9VZGlV7RRT-SueOY1gI5682P?usp=drive_link"],
      ["Creating DAX measures in Power BI practise round", "Google Drive", "https://drive.google.com/drive/folders/1hIXsD6az9VZGlV7RRT-SueOY1gI5682P?usp=drive_link"],
      ["Flexibility of DAX Measures why they are so great", "Google Drive", "https://drive.google.com/drive/folders/1hIXsD6az9VZGlV7RRT-SueOY1gI5682P?usp=drive_link"],
      ["Dates and Drilldown functionality in Power BI", "Google Drive", "https://drive.google.com/drive/folders/1hIXsD6az9VZGlV7RRT-SueOY1gI5682P?usp=drive_link"],
      ["Additional info to the Auto datetime feature in Power BI", "Google Drive", "https://drive.google.com/drive/folders/1hIXsD6az9VZGlV7RRT-SueOY1gI5682P?usp=drive_link"],
      ["Timeintelligence DAX Calculations in Power BI getting started", "Google Drive", "https://drive.google.com/drive/folders/1hIXsD6az9VZGlV7RRT-SueOY1gI5682P?usp=drive_link"],
      ["Timeintelligence DAX Calculations in Power BI more flexibility", "Google Drive", "https://drive.google.com/drive/folders/1hIXsD6az9VZGlV7RRT-SueOY1gI5682P?usp=drive_link"],
      ["Timeintelligence DAX Calculations Cumulative Sum or Running Totals", "Google Drive", "https://drive.google.com/drive/folders/1hIXsD6az9VZGlV7RRT-SueOY1gI5682P?usp=drive_link"],
      ["DAX Measure Cleanup and Formatting best practise", "Google Drive", "https://drive.google.com/drive/folders/1hIXsD6az9VZGlV7RRT-SueOY1gI5682P?usp=drive_link"],
      ["The final Power BI Report creation", "Google Drive", "https://drive.google.com/drive/folders/1hIXsD6az9VZGlV7RRT-SueOY1gI5682P?usp=drive_link"],
      ["Advanced Training 2 New dataset setup", "Google Drive", "https://drive.google.com/drive/folders/1hIXsD6az9VZGlV7RRT-SueOY1gI5682P?usp=drive_link"],
      ["Practising DAX measures and Bulk Formatting Tricks", "Google Drive", "https://drive.google.com/drive/folders/1hIXsD6az9VZGlV7RRT-SueOY1gI5682P?usp=drive_link"],
      ["DAX Timeintelligence different Functions allow different Insights", "Google Drive", "https://drive.google.com/drive/folders/1hIXsD6az9VZGlV7RRT-SueOY1gI5682P?usp=drive_link"],
      ["Ranking and dynamic Ranking in Power BI", "Google Drive", "https://drive.google.com/drive/folders/1hIXsD6az9VZGlV7RRT-SueOY1gI5682P?usp=drive_link"],
      ["Power BI DAX Expressions Cumulative Sales for the prior year", "Google Drive", "https://drive.google.com/drive/folders/1hIXsD6az9VZGlV7RRT-SueOY1gI5682P?usp=drive_link"],
      ["Introduction to Scenario Analysis in Power BI", "Google Drive", "https://drive.google.com/drive/folders/1hIXsD6az9VZGlV7RRT-SueOY1gI5682P?usp=drive_link"],
      ["Rolling 30 day Sales DAX Expression", "Google Drive", "https://drive.google.com/drive/folders/1hIXsD6az9VZGlV7RRT-SueOY1gI5682P?usp=drive_link"],
      ["DAX Table functions in Power BI lets get into it", "Google Drive", "https://drive.google.com/drive/folders/1hIXsD6az9VZGlV7RRT-SueOY1gI5682P?usp=drive_link"],
      ["Advanced DAX Top 10 Customers", "Google Drive", "https://drive.google.com/drive/folders/1hIXsD6az9VZGlV7RRT-SueOY1gI5682P?usp=drive_link"],
      ["Customer Insights How many customers by weekday", "Google Drive", "https://drive.google.com/drive/folders/1hIXsD6az9VZGlV7RRT-SueOY1gI5682P?usp=drive_link"],
      ["DAX or No DAX that is the question", "Google Drive", "https://drive.google.com/drive/folders/1hIXsD6az9VZGlV7RRT-SueOY1gI5682P?usp=drive_link"],
      ["Advanced DAX Customer Classification", "Google Drive", "https://drive.google.com/drive/folders/1hIXsD6az9VZGlV7RRT-SueOY1gI5682P?usp=drive_link"],
      ["Introducing Variables while calculating Weekday Sales", "Google Drive", "https://drive.google.com/drive/folders/1hIXsD6az9VZGlV7RRT-SueOY1gI5682P?usp=drive_link"],
      ["Lets create our final report", "Google Drive", "https://drive.google.com/drive/folders/1hIXsD6az9VZGlV7RRT-SueOY1gI5682P?usp=drive_link"],
      ["Addon Buttons and Page Navigation in Power BI", "Google Drive", "https://drive.google.com/drive/folders/1hIXsD6az9VZGlV7RRT-SueOY1gI5682P?usp=drive_link"],
      ["Congratulations and Motivation", "Google Drive", "https://drive.google.com/drive/folders/1hIXsD6az9VZGlV7RRT-SueOY1gI5682P?usp=drive_link"],
      ["Power BI Masterclass - Beginners to Advanced Introduction", "Google Drive", "https://drive.google.com/drive/folders/1yvOET51CK0zK7E8pfIRz0N82cJnvwCsx?usp=drive_link"],
      ["A First Tour Through the Power BI Interface", "Google Drive", "https://drive.google.com/drive/folders/1yvOET51CK0zK7E8pfIRz0N82cJnvwCsx?usp=drive_link"],
      ["Power BI the Easy Way - Let's Get Started", "Google Drive", "https://drive.google.com/drive/folders/1yvOET51CK0zK7E8pfIRz0N82cJnvwCsx?usp=drive_link"],
      ["Power BI the Easy Way - Let's Finish Our First Report in Power BI Desktop", "Google Drive", "https://drive.google.com/drive/folders/1yvOET51CK0zK7E8pfIRz0N82cJnvwCsx?usp=drive_link"],
      ["Power BI the Advanced Way - Let's Dive into Our Dataset", "Google Drive", "https://drive.google.com/drive/folders/1yvOET51CK0zK7E8pfIRz0N82cJnvwCsx?usp=drive_link"],
      ["The Power BI Query Editor - Data Preparation in Action", "Google Drive", "https://drive.google.com/drive/folders/1yvOET51CK0zK7E8pfIRz0N82cJnvwCsx?usp=drive_link"],
      ["Import the New and Advanced Date Table into Our Model", "Google Drive", "https://drive.google.com/drive/folders/1yvOET51CK0zK7E8pfIRz0N82cJnvwCsx?usp=drive_link"],
      ["Walk Through Transformation Steps in Power Query Editor", "Google Drive", "https://drive.google.com/drive/folders/1yvOET51CK0zK7E8pfIRz0N82cJnvwCsx?usp=drive_link"],
      ["Data Enrichment Importing Web Data into Power BI", "Google Drive", "https://drive.google.com/drive/folders/1yvOET51CK0zK7E8pfIRz0N82cJnvwCsx?usp=drive_link"],
      ["Exploring the Model View and Setting Up Relationships", "Google Drive", "https://drive.google.com/drive/folders/1yvOET51CK0zK7E8pfIRz0N82cJnvwCsx?usp=drive_link"],
      ["First Calculations in Power BI Calculated Columns and Measures", "Google Drive", "https://drive.google.com/drive/folders/1yvOET51CK0zK7E8pfIRz0N82cJnvwCsx?usp=drive_link"],
      ["The Measures Table Trick - Structuring Our Report", "Google Drive", "https://drive.google.com/drive/folders/1yvOET51CK0zK7E8pfIRz0N82cJnvwCsx?usp=drive_link"],
      ["Power BI DAX - Practice Creating Further Measures", "Google Drive", "https://drive.google.com/drive/folders/1yvOET51CK0zK7E8pfIRz0N82cJnvwCsx?usp=drive_link"],
      ["The Beauty of Flexibility - Power BI Slicing and Dicing", "Google Drive", "https://drive.google.com/drive/folders/1yvOET51CK0zK7E8pfIRz0N82cJnvwCsx?usp=drive_link"],
      ["Date Drill Down Functionalities in Power BI", "Google Drive", "https://drive.google.com/drive/folders/1yvOET51CK0zK7E8pfIRz0N82cJnvwCsx?usp=drive_link"],
      ["Autodatetime in Power BI - What You Need to Know About Date Hierarchies", "Google Drive", "https://drive.google.com/drive/folders/1yvOET51CK0zK7E8pfIRz0N82cJnvwCsx?usp=drive_link"],
      ["Advanced DAX - Intro to Time Intelligence DAX Measures", "Google Drive", "https://drive.google.com/drive/folders/1yvOET51CK0zK7E8pfIRz0N82cJnvwCsx?usp=drive_link"],
      ["Advanced DAX - Flexibility in Time Intelligence DAX Functions", "Google Drive", "https://drive.google.com/drive/folders/1yvOET51CK0zK7E8pfIRz0N82cJnvwCsx?usp=drive_link"],
      ["Advanced DAX - Cumulative or Running Total Sales Calculation in DAX", "Google Drive", "https://drive.google.com/drive/folders/1yvOET51CK0zK7E8pfIRz0N82cJnvwCsx?usp=drive_link"],
      ["Power BI - Let's Create Our Final Report", "Google Drive", "https://drive.google.com/drive/folders/1yvOET51CK0zK7E8pfIRz0N82cJnvwCsx?usp=drive_link"],
      ["Welcome to Part 2 - Setting Up Our New Model Structure", "Google Drive", "https://drive.google.com/drive/folders/1yvOET51CK0zK7E8pfIRz0N82cJnvwCsx?usp=drive_link"],
      ["Power BI DAX - Creating Our Base Measures", "Google Drive", "https://drive.google.com/drive/folders/1yvOET51CK0zK7E8pfIRz0N82cJnvwCsx?usp=drive_link"],
      ["Advanced Time Intelligence in DAX - Parallel Period and Potential Use Cases", "Google Drive", "https://drive.google.com/drive/folders/1yvOET51CK0zK7E8pfIRz0N82cJnvwCsx?usp=drive_link"],
      ["Advanced DAX - Dynamic Sales Rankings", "Google Drive", "https://drive.google.com/drive/folders/1yvOET51CK0zK7E8pfIRz0N82cJnvwCsx?usp=drive_link"],
      ["Advanced DAX - Running Total Sales and Prior Year Sales", "Google Drive", "https://drive.google.com/drive/folders/1yvOET51CK0zK7E8pfIRz0N82cJnvwCsx?usp=drive_link"],
      ["Power BI - Visualizing Insights from Our Data", "Google Drive", "https://drive.google.com/drive/folders/1yvOET51CK0zK7E8pfIRz0N82cJnvwCsx?usp=drive_link"],
      ["Scenario Analysis in Power BI", "Google Drive", "https://drive.google.com/drive/folders/1yvOET51CK0zK7E8pfIRz0N82cJnvwCsx?usp=drive_link"],
      ["Advanced DAX - Running Total X Day Sales", "Google Drive", "https://drive.google.com/drive/folders/1yvOET51CK0zK7E8pfIRz0N82cJnvwCsx?usp=drive_link"],
      ["DAX - An Introduction to Table Functions", "Google Drive", "https://drive.google.com/drive/folders/1yvOET51CK0zK7E8pfIRz0N82cJnvwCsx?usp=drive_link"],
      ["Advanced DAX - What Are the Top 10 Clients", "Google Drive", "https://drive.google.com/drive/folders/1yvOET51CK0zK7E8pfIRz0N82cJnvwCsx?usp=drive_link"],
      ["Advanced DAX - How Many Customers per Weekday", "Google Drive", "https://drive.google.com/drive/folders/1yvOET51CK0zK7E8pfIRz0N82cJnvwCsx?usp=drive_link"],
      ["Power BI DAX or No DAX - That Is the Question", "Google Drive", "https://drive.google.com/drive/folders/1yvOET51CK0zK7E8pfIRz0N82cJnvwCsx?usp=drive_link"],
      ["Advanced DAX - Customer Classification in Power BI", "Google Drive", "https://drive.google.com/drive/folders/1yvOET51CK0zK7E8pfIRz0N82cJnvwCsx?usp=drive_link"],
      ["Advanced DAX - Variables and Sales per Weekday and Weekends", "Google Drive", "https://drive.google.com/drive/folders/1yvOET51CK0zK7E8pfIRz0N82cJnvwCsx?usp=drive_link"],
      ["Create Our Final Report in Power BI", "Google Drive", "https://drive.google.com/drive/folders/1yvOET51CK0zK7E8pfIRz0N82cJnvwCsx?usp=drive_link"],
      ["Introduction to the CALCULATE Function Starting from Scratch", "Google Drive", "https://drive.google.com/drive/folders/1p2rsOFrjpan7Qw6wkkmTGojMSJWJ2Rk-?usp=drive_link"],
      ["Filter Contexts, Row Context and Context Transition in Power BI Explained", "Google Drive", "https://drive.google.com/drive/folders/1p2rsOFrjpan7Qw6wkkmTGojMSJWJ2Rk-?usp=drive_link"],
      ["Combine CALCULATE with ALL and VALUES", "Google Drive", "https://drive.google.com/drive/folders/1p2rsOFrjpan7Qw6wkkmTGojMSJWJ2Rk-?usp=drive_link"],
      ["Dynamic Selection with CALCULATE", "Google Drive", "https://drive.google.com/drive/folders/1p2rsOFrjpan7Qw6wkkmTGojMSJWJ2Rk-?usp=drive_link"],
      ["How to Apply Multiple Criteria Filter with CALCULATE in Power BI", "Google Drive", "https://drive.google.com/drive/folders/1p2rsOFrjpan7Qw6wkkmTGojMSJWJ2Rk-?usp=drive_link"],
      ["How to Use Multiple Filter Criteria with CALCULATE in Power BI", "Google Drive", "https://drive.google.com/drive/folders/1p2rsOFrjpan7Qw6wkkmTGojMSJWJ2Rk-?usp=drive_link"],
      ["CALCULATE with Multiple Criteria from Different Columns in Power BI", "Google Drive", "https://drive.google.com/drive/folders/1p2rsOFrjpan7Qw6wkkmTGojMSJWJ2Rk-?usp=drive_link"],
      ["Sales Classification Using CALCULATE", "Google Drive", "https://drive.google.com/drive/folders/1p2rsOFrjpan7Qw6wkkmTGojMSJWJ2Rk-?usp=drive_link"],
      ["Cleaning Up and Quickly Set Up the New Model", "Google Drive", "https://drive.google.com/drive/folders/1p2rsOFrjpan7Qw6wkkmTGojMSJWJ2Rk-?usp=drive_link"],
      ["Applying ALL and ALLSELECTED with CALCULATE in Power BI", "Google Drive", "https://drive.google.com/drive/folders/1p2rsOFrjpan7Qw6wkkmTGojMSJWJ2Rk-?usp=drive_link"],
      ["CALCULATE with the KEEPFILTERS Modifier", "Google Drive", "https://drive.google.com/drive/folders/1p2rsOFrjpan7Qw6wkkmTGojMSJWJ2Rk-?usp=drive_link"],
      ["Modify Model Relationships with CALCULATE", "Google Drive", "https://drive.google.com/drive/folders/1p2rsOFrjpan7Qw6wkkmTGojMSJWJ2Rk-?usp=drive_link"],
      ["Visual Understanding of the Expanded Table Concept", "Google Drive", "https://drive.google.com/drive/folders/1p2rsOFrjpan7Qw6wkkmTGojMSJWJ2Rk-?usp=drive_link"],
      ["CALCULATE Modifiers Remove All Filters Except One", "Google Drive", "https://drive.google.com/drive/folders/1p2rsOFrjpan7Qw6wkkmTGojMSJWJ2Rk-?usp=drive_link"],
      ["Using CALCULATE with Time Intelligence Expressions", "Google Drive", "https://drive.google.com/drive/folders/1p2rsOFrjpan7Qw6wkkmTGojMSJWJ2Rk-?usp=drive_link"],
      ["Bonus Section","Google Drive", "https://drive.google.com/drive/folders/1ctaXZQDuM1mXQnNwBAAdIo8jrUPiNPLj?usp=drive_link"],
    ],
  },
  "peachtree": {
    label: "Microsoft Peach Tree",
    title: "Microsoft Peach Tree Learning Section",
    description: "Company setup, inventory, sales purchase workflow, reports, and adjustments.",
    image: "../assets/Peachtree.jpg",
    price: "Rs 999",
    payment: "../payment.html?course=Microsoft%20Peachtree&price=Rs%20999",
    topics: [
      ["Welcome to Peachtree.", "Drive Video", "https://drive.google.com/drive/folders/19ufRgEQD4FrrDcJYuDuLYx876DK8aMeT?usp=drive_link"],
      ["Installation of Peachtree Software.", "Drive Video", "https://drive.google.com/drive/folders/19ufRgEQD4FrrDcJYuDuLYx876DK8aMeT?usp=drive_link"],
      ["Customizing Dashboard in Peachtree", "Drive Video", "https://drive.google.com/drive/folders/19ufRgEQD4FrrDcJYuDuLYx876DK8aMeT?usp=drive_link"],
      ["Customizing Chart of Accounts.", "Drive Video", "https://drive.google.com/drive/folders/19ufRgEQD4FrrDcJYuDuLYx876DK8aMeT?usp=drive_link"],
      ["Creating New COA and Customizing Existing.", "Drive Video", "https://drive.google.com/drive/folders/19ufRgEQD4FrrDcJYuDuLYx876DK8aMeT?usp=drive_link"],
      ["Entering Opening Balances in COA.", "Drive Video", "https://drive.google.com/drive/folders/19ufRgEQD4FrrDcJYuDuLYx876DK8aMeT?usp=drive_link"],
      ["Extracting Trial Balance in Peachtree", "Drive Video", "https://drive.google.com/drive/folders/19ufRgEQD4FrrDcJYuDuLYx876DK8aMeT?usp=drive_link"],
      ["Repositioning and Customizing Report Columns", "Drive Video", "https://drive.google.com/drive/folders/19ufRgEQD4FrrDcJYuDuLYx876DK8aMeT?usp=drive_link"],
      ["Entering Customer Balances In Peachtree.", "Drive Video", "https://drive.google.com/drive/folders/19ufRgEQD4FrrDcJYuDuLYx876DK8aMeT?usp=drive_link"],
      ["Entering Vendors Balances.", "Drive Video", "https://drive.google.com/drive/folders/19ufRgEQD4FrrDcJYuDuLYx876DK8aMeT?usp=drive_link"],
      ["Entering Inventory Items in Peachtree.", "Drive Video", "https://drive.google.com/drive/folders/19ufRgEQD4FrrDcJYuDuLYx876DK8aMeT?usp=drive_link"],
      ["Add Opening Balance to Inventory.", "Drive Video", "https://drive.google.com/drive/folders/19ufRgEQD4FrrDcJYuDuLYx876DK8aMeT?usp=drive_link"],
      ["Reconciling Opening Trial Before Day to Day Entries.", "Drive Video", "https://drive.google.com/drive/folders/19ufRgEQD4FrrDcJYuDuLYx876DK8aMeT?usp=drive_link"],
      ["Entering Day To Day Entries in Peachtree.", "Drive Video", "https://drive.google.com/drive/folders/19ufRgEQD4FrrDcJYuDuLYx876DK8aMeT?usp=drive_link"],
      ["Entering Prepaid Expenses in Peachtree", "Drive Video", "https://drive.google.com/drive/folders/19ufRgEQD4FrrDcJYuDuLYx876DK8aMeT?usp=drive_link"],
      ["Dealing With Office Security Deposit.", "Drive Video", "https://drive.google.com/drive/folders/19ufRgEQD4FrrDcJYuDuLYx876DK8aMeT?usp=drive_link"],
      ["Dealing With Repair and Maintenance Expenses in Peachtree.", "Drive Video", "https://drive.google.com/drive/folders/19ufRgEQD4FrrDcJYuDuLYx876DK8aMeT?usp=drive_link"],
      ["Receiving Payments from Customers.", "Drive Video", "https://drive.google.com/drive/folders/19ufRgEQD4FrrDcJYuDuLYx876DK8aMeT?usp=drive_link"],
      ["Entering Purchase Invoice in Peachtree.", "Drive Video", "https://drive.google.com/drive/folders/19ufRgEQD4FrrDcJYuDuLYx876DK8aMeT?usp=drive_link"],
      ["Recording Purchase Invoice With New Vendor.", "Drive Video", "https://drive.google.com/drive/folders/19ufRgEQD4FrrDcJYuDuLYx876DK8aMeT?usp=drive_link"],
      ["Cash Sales In Peachtree.", "Drive Video", "https://drive.google.com/drive/folders/19ufRgEQD4FrrDcJYuDuLYx876DK8aMeT?usp=drive_link"],
      ["Dealing With Customer Advances.", "Drive Video", "https://drive.google.com/drive/folders/19ufRgEQD4FrrDcJYuDuLYx876DK8aMeT?usp=drive_link"],
      ["Recording Sales Order In Peachtree", "Drive Video", "https://drive.google.com/drive/folders/19ufRgEQD4FrrDcJYuDuLYx876DK8aMeT?usp=drive_link"],
      ["Recording Credit Sales Invoice Against Customer", "Drive Video", "https://drive.google.com/drive/folders/19ufRgEQD4FrrDcJYuDuLYx876DK8aMeT?usp=drive_link"],
      ["Dealing With Purchase Orders In Peachtree", "Drive Video", "https://drive.google.com/drive/folders/19ufRgEQD4FrrDcJYuDuLYx876DK8aMeT?usp=drive_link"],
      ["How to Record Bad Debt in Peachtree", "Drive Video", "https://drive.google.com/drive/folders/19ufRgEQD4FrrDcJYuDuLYx876DK8aMeT?usp=drive_link"],
      ["Record Service Invoice in Peachtree", "Drive Video", "https://drive.google.com/drive/folders/19ufRgEQD4FrrDcJYuDuLYx876DK8aMeT?usp=drive_linkq"],
      ["Payment Against Service Invoice", "Drive Video", "https://drive.google.com/drive/folders/19ufRgEQD4FrrDcJYuDuLYx876DK8aMeT?usp=drive_link"],
      ["Convert Sales Order to Sales Invoice", "Drive Video", "https://drive.google.com/drive/folders/19ufRgEQD4FrrDcJYuDuLYx876DK8aMeT?usp=drive_link"],
      ["How to Adjust Credit Limit for Customers in Payment Terms", "Drive Video", "https://drive.google.com/drive/folders/19ufRgEQD4FrrDcJYuDuLYx876DK8aMeT?usp=drive_link"],
      ["Dealing With Purchase Returns In Peachtree", "Drive Video", "https://drive.google.com/drive/folders/19ufRgEQD4FrrDcJYuDuLYx876DK8aMeT?usp=drive_link"],
      ["Dealing With Sales Return In Peachtree", "Drive Video", "https://drive.google.com/drive/folders/19ufRgEQD4FrrDcJYuDuLYx876DK8aMeT?usp=drive_link"],
      ["Receiving Payment Due from Customer", "Drive Video", "https://drive.google.com/drive/folders/19ufRgEQD4FrrDcJYuDuLYx876DK8aMeT?usp=drive_link"],
      ["Create Purchase Invoice from Purchase Order", "Drive Video", "https://drive.google.com/drive/folders/19ufRgEQD4FrrDcJYuDuLYx876DK8aMeT?usp=drive_link"],
      ["Recording Loss of Inventory in Peachtree", "Drive Video", "https://drive.google.com/drive/folders/19ufRgEQD4FrrDcJYuDuLYx876DK8aMeT?usp=drive_link"],
      ["Loss of Inventory Explanation", "Drive Video", "https://drive.google.com/drive/folders/19ufRgEQD4FrrDcJYuDuLYx876DK8aMeT?usp=drive_link"],
      ["Unwinding Prepaid Expenses in Peachtree", "Drive Video", "https://drive.google.com/drive/folders/19ufRgEQD4FrrDcJYuDuLYx876DK8aMeT?usp=drive_link"],
      ["Extracting and Reconciling Closing Month End Reports", "Drive Video", "https://drive.google.com/drive/folders/19ufRgEQD4FrrDcJYuDuLYx876DK8aMeT?usp=drive_link"],
      ["Introduction to Manufacturing Company", "Drive Video", "https://drive.google.com/drive/folders/19ufRgEQD4FrrDcJYuDuLYx876DK8aMeT?usp=drive_link"],
      ["Creating a New Manufacturing Company", "Drive Video", "https://drive.google.com/drive/folders/19ufRgEQD4FrrDcJYuDuLYx876DK8aMeT?usp=drive_link"],
      ["Creating a New Manufacturing Company", "Drive Video", "https://drive.google.com/drive/folders/19ufRgEQD4FrrDcJYuDuLYx876DK8aMeT?usp=drive_link"],
    ],
  },
  "sap-s4-hana": {
    label: "SAP 4 HANA",
    title: "SAP 4 HANA Learning Section",
    description: "SAP S4 HANA navigation, Fiori, finance modules, master data, and reporting.",
    image: "../assets/SAP S4 HANA.jpg",
    price: "Rs 999",
    payment: "../payment.html?course=SAP%20S4%20HANA&price=Rs%20999",
    topics: [
     ["What you should know before taking the course", "Google Drive", "https://drive.google.com/drive/folders/1FKkF3mvtBPLyT5SCT-KRtSRGlkT6gkwc?usp=drive_link"],
     ["Understand the key aspects of SAP Business Suite", "Google Drive", "https://drive.google.com/drive/folders/1Fi9XdX9NydkFM6AhHvaulO7vrMnwySB7?usp=drive_link"],
     ["Understand the key aspects of SAP S4 HANA", "Google Drive", "https://drive.google.com/drive/folders/1Fi9XdX9NydkFM6AhHvaulO7vrMnwySB7?usp=drive_link"],
     ["Benefits and limitations of using SAP", "Google Drive", "https://drive.google.com/drive/folders/1Fi9XdX9NydkFM6AhHvaulO7vrMnwySB7?usp=drive_link"],
     ["Build business case for SAP S4HANA", "Google Drive", "https://drive.google.com/drive/folders/1Fi9XdX9NydkFM6AhHvaulO7vrMnwySB7?usp=drive_link"],
     ["Introduce the demo company of this course", "Google Drive", "https://drive.google.com/drive/folders/1Fi9XdX9NydkFM6AhHvaulO7vrMnwySB7?usp=drive_link"],
     ["Create a logon system", "Google Drive", "https://drive.google.com/drive/folders/1zuJG2a6ihFb-8Jf0p_l-ybMBou2bFMrs?usp=drive_link"],
     ["Log on to SAP GUI", "Google Drive", "https://drive.google.com/drive/folders/1zuJG2a6ihFb-8Jf0p_l-ybMBou2bFMrs?usp=drive_link"],
     ["Work with different toolbars", "Google Drive", "https://drive.google.com/drive/folders/1zuJG2a6ihFb-8Jf0p_l-ybMBou2bFMrs?usp=drive_link"],
     ["Add a new item to favorites", "Google Drive", "https://drive.google.com/drive/folders/1zuJG2a6ihFb-8Jf0p_l-ybMBou2bFMrs?usp=drive_link"],
     ["Work with SAP command field", "Google Drive", "https://drive.google.com/drive/folders/1zuJG2a6ihFb-8Jf0p_l-ybMBou2bFMrs?usp=drive_link"],
     ["Work with SAP Help", "Google Drive", "https://drive.google.com/drive/folders/1zuJG2a6ihFb-8Jf0p_l-ybMBou2bFMrs?usp=drive_link"],
     ["Personalize your own data", "Google Drive", "https://drive.google.com/drive/folders/1zuJG2a6ihFb-8Jf0p_l-ybMBou2bFMrs?usp=drive_link"],
     ["Bonus Navigate in the latest SAP GUI (Version 750)", "Google Drive", "https://drive.google.com/drive/folders/1zuJG2a6ihFb-8Jf0p_l-ybMBou2bFMrs?usp=drive_link"],
     ["Understand SAP Fiori", "Google Drive", "https://drive.google.com/drive/folders/1FFMuykTYGhy3cyFUPXUGlqnZ3fpbZY_U?usp=drive_link"],
     ["Fiori apps reference library", "Google Drive", "https://drive.google.com/drive/folders/1FFMuykTYGhy3cyFUPXUGlqnZ3fpbZY_U?usp=drive_link"],
     ["Generate Fiori apps recommendations report", "Google Drive", "https://drive.google.com/drive/folders/1FFMuykTYGhy3cyFUPXUGlqnZ3fpbZY_U?usp=drive_link"],
     ["How to navigate SAP Fiori launchpad", "Google Drive", "https://drive.google.com/drive/folders/1FFMuykTYGhy3cyFUPXUGlqnZ3fpbZY_U?usp=drive_link"],
     ["Understand organizational unit, element, structure", "Google Drive", "https://drive.google.com/drive/folders/1LI3bH68Vw7ovYzP5_X4_Ty-uLpOnl1sg?usp=drive_link"],
     ["Explore master data", "Google Drive", "https://drive.google.com/drive/folders/1LI3bH68Vw7ovYzP5_X4_Ty-uLpOnl1sg?usp=drive_link"],
     ["Display a material master record via Fiori Launchpad", "Google Drive", "https://drive.google.com/drive/folders/1LI3bH68Vw7ovYzP5_X4_Ty-uLpOnl1sg?usp=drive_link"],
     ["Display a customer master data via Fiori Launchpad", "Google Drive", "https://drive.google.com/drive/folders/1LI3bH68Vw7ovYzP5_X4_Ty-uLpOnl1sg?usp=drive_link"],
     ["Display a customer master data via GUI", "Google Drive", "https://drive.google.com/drive/folders/1LI3bH68Vw7ovYzP5_X4_Ty-uLpOnl1sg?usp=drive_link"],
     ["Display a business partner via Fiori Launchpad", "Google Drive", "https://drive.google.com/drive/folders/1LI3bH68Vw7ovYzP5_X4_Ty-uLpOnl1sg?usp=drive_link"],
     ["Enterprise Management (previously logistics)", "Google Drive", "https://drive.google.com/drive/folders/1SZKDZsw_9fMHFRcMbkgdeg3JcskwHplC?usp=drive_link"],
     ["Integrated modules and systems", "Google Drive", "https://drive.google.com/drive/folders/1OhfiRNsXHfD3aXYJlnt9vPgjJRUf5Lb9?usp=drive_link"],
     ["Organization structures", "Google Drive", "https://drive.google.com/drive/folders/1OhfiRNsXHfD3aXYJlnt9vPgjJRUf5Lb9?usp=drive_link"],
     ["Organization elements", "Google Drive", "https://drive.google.com/drive/folders/1OhfiRNsXHfD3aXYJlnt9vPgjJRUf5Lb9?usp=drive_link"],
     ["Core finance modules", "Google Drive", "https://drive.google.com/drive/folders/1OhfiRNsXHfD3aXYJlnt9vPgjJRUf5Lb9?usp=drive_link"],
     ["Recording Corporate Value Flow I - Purchase to Pay", "Google Drive", "https://drive.google.com/drive/folders/1OhfiRNsXHfD3aXYJlnt9vPgjJRUf5Lb9?usp=drive_link"],
     ["Accounts Payable Invoice and Outgoing Payment", "Google Drive", "https://drive.google.com/drive/folders/1OhfiRNsXHfD3aXYJlnt9vPgjJRUf5Lb9?usp=drive_link"],
     ["Recording Corporate Value Flow II - Order to Cash", "Google Drive", "https://drive.google.com/drive/folders/1OhfiRNsXHfD3aXYJlnt9vPgjJRUf5Lb9?usp=drive_link"],
     ["Accounts Receivable Accounting", "Google Drive", "https://drive.google.com/drive/folders/1OhfiRNsXHfD3aXYJlnt9vPgjJRUf5Lb9?usp=drive_link"],
     ["Recording Corporate Value Flow III - Plan to Product", "Google Drive", "https://drive.google.com/drive/folders/1OhfiRNsXHfD3aXYJlnt9vPgjJRUf5Lb9?usp=drive_link"],
     ["Product Cost Controlling", "Google Drive", "https://drive.google.com/drive/folders/1OhfiRNsXHfD3aXYJlnt9vPgjJRUf5Lb9?usp=drive_link"],
     ["Balance Sheet and Profit and Loss Statement", "Google Drive", "https://drive.google.com/drive/folders/1OhfiRNsXHfD3aXYJlnt9vPgjJRUf5Lb9?usp=drive_link"],
     ["Cost Center Accounting", "Google Drive", "https://drive.google.com/drive/folders/1OhfiRNsXHfD3aXYJlnt9vPgjJRUf5Lb9?usp=drive_link"],
     ["Profitability Analysis", "Google Drive", "https://drive.google.com/drive/folders/1OhfiRNsXHfD3aXYJlnt9vPgjJRUf5Lb9?usp=drive_link"],
     ["What_s Human Capital Management", "Google Drive", "https://drive.google.com/drive/folders/1KFHuQBIO1nYb9m6jardzcRX_wtlv2oWp?usp=drive_link"],
     ["Understand Human Capital Management", "Google Drive", "https://drive.google.com/drive/folders/1KFHuQBIO1nYb9m6jardzcRX_wtlv2oWp?usp=drive_link"],
     ["Display an Employee Profile and Assign a Position", "Google Drive", "https://drive.google.com/drive/folders/1KFHuQBIO1nYb9m6jardzcRX_wtlv2oWp?usp=drive_link"],
     ["Understand embedded analytics in S4 HANA", "Google Drive", "https://drive.google.com/drive/folders/1w_0YOLQGIV4OEQnbNQb8fQsM0c7kKk2k?usp=drive_link"],
     ["Text processing", "Google Drive", "https://drive.google.com/drive/folders/1Z4dlQt0wWFzuOnhGGfRFjxp-sG58sjAJ?usp=drive_link"],
     ["Spatial analysis", "Google Drive", "https://drive.google.com/drive/folders/1Z4dlQt0wWFzuOnhGGfRFjxp-sG58sjAJ?usp=drive_link"],
     ["Graph processing", "Google Drive", "https://drive.google.com/drive/folders/1Z4dlQt0wWFzuOnhGGfRFjxp-sG58sjAJ?usp=drive_link"],
     ["Disaster recovery", "Google Drive", "https://drive.google.com/drive/folders/1Z4dlQt0wWFzuOnhGGfRFjxp-sG58sjAJ?usp=drive_link"],
     ["How to size HANA database", "Google Drive", "https://drive.google.com/drive/folders/1Z4dlQt0wWFzuOnhGGfRFjxp-sG58sjAJ?usp=drive_link"],
     ["Implement SAP", "Google Drive", "https://drive.google.com/drive/folders/1CpmEeuaviRsvbTIJe-1rlYSv9fASvOg9?usp=drive_link"],
     ["Conclusion", "Google Drive", "https://drive.google.com/drive/folders/1dccYUCptkbt1N6EGVSBzRD-qXuXgJS9L?usp=drive_link"],
    ]
  },
  "sap-fico": {
    label: "SAP FICO",
    title: "SAP FICO Learning Section",
    description: "General ledger, accounts payable, cost centers, GL master, and finance basics.",
    image: "../assets/SAP-FICO.jpg",
    price: "Rs 999",
    payment: "../payment.html?course=SAP%20FICO&price=Rs%20999",
    topics: [
      ["Basic Overview of SAP.", "Drive Video", "https://drive.google.com/drive/folders/1YjGEclAgQy8qwFcAj_NVNIjmIThTKkCK?usp=drive_link"],
      ["Types of SAP Projects.", "Drive Video", "https://drive.google.com/drive/folders/1YjGEclAgQy8qwFcAj_NVNIjmIThTKkCK?usp=drive_link"],
      ["ASAP Methodology_1.", "Drive Video", "https://drive.google.com/drive/folders/1YjGEclAgQy8qwFcAj_NVNIjmIThTKkCK?usp=drive_link"],
      ["ASAP Methodology_2.", "Drive Video", "https://drive.google.com/drive/folders/1YjGEclAgQy8qwFcAj_NVNIjmIThTKkCK?usp=drive_link"],
      ["Small Request.", "Drive Video", "https://drive.google.com/drive/folders/1_t4pv6RWqvs48EQjhnY2XTtsVFfN8H8l?usp=drive_link"],
      ["Enterprise Structure_1.", "Drive Video", "https://drive.google.com/drive/folders/1_t4pv6RWqvs48EQjhnY2XTtsVFfN8H8l?usp=drive_link"],
      ["Posting Period Variant_1.", "Drive Video", "https://drive.google.com/drive/folders/1gWXum4N2DuUfDyRr-aA1_tCspJxAUmPA?usp=drive_link"],
      ["Number Range.", "Drive Video", "https://drive.google.com/drive/folders/1gWXum4N2DuUfDyRr-aA1_tCspJxAUmPA?usp=drive_link"],
      ["Tolerance Group_1.", "Drive Video", "https://drive.google.com/drive/folders/1gWXum4N2DuUfDyRr-aA1_tCspJxAUmPA?usp=drive_link"],
      ["Tolerance Group_2.", "Drive Video", "https://drive.google.com/drive/folders/1gWXum4N2DuUfDyRr-aA1_tCspJxAUmPA?usp=drive_link"],
      ["Announcement of free enrollment.", "Drive Video", "https://drive.google.com/drive/folders/1BuEY_qhWD3_BgtRgyVLdvwN-mnlPCq0r?usp=drive_link"],
      ["Chart of Account.", "Drive Video", "https://drive.google.com/drive/folders/1UgjRrLjtYZ63cYvBM1mtHb8StC9WaEd7?usp=drive_link"],
      ["Account Group.", "Drive Video", "https://drive.google.com/drive/folders/1UgjRrLjtYZ63cYvBM1mtHb8StC9WaEd7?usp=drive_link"],
      ["GL Master_Creation.", "Drive Video", "https://drive.google.com/drive/folders/1UgjRrLjtYZ63cYvBM1mtHb8StC9WaEd7?usp=drive_link"],
      ["GL Master_Field Status Control.", "Drive Video", "https://drive.google.com/drive/folders/1UgjRrLjtYZ63cYvBM1mtHb8StC9WaEd7?usp=drive_link"],
      ["Document Posting_F-02.", "Drive Video", "https://drive.google.com/drive/folders/1hDzEsbrkYt_Fk_dAoeXhWtlp9GQVoZaE?usp=drive_link"],
      ["Document Posting_FB50.", "Drive Video", "https://drive.google.com/drive/folders/1hDzEsbrkYt_Fk_dAoeXhWtlp9GQVoZaE?usp=drive_link"],
      ["Document Posting_Field Status Control.", "Drive Video", "https://drive.google.com/drive/folders/1hDzEsbrkYt_Fk_dAoeXhWtlp9GQVoZaE?usp=drive_link"],
      ["Document Posting_Field Status Control.", "Drive Video", "https://drive.google.com/drive/folders/1hDzEsbrkYt_Fk_dAoeXhWtlp9GQVoZaE?usp=drive_link"],
      ["Document Reversal.", "Drive Video", "https://drive.google.com/drive/folders/1hDzEsbrkYt_Fk_dAoeXhWtlp9GQVoZaE?usp=drive_link"],
      ["Foregin Currency setting's", "Drive Video", "https://drive.google.com/drive/folders/1uthcqU214iNypL0J7Zxu7fn0HkWudNTx?usp=drive_link"],
      ["Hold Document.", "Drive Video", "https://drive.google.com/drive/folders/1hDzEsbrkYt_Fk_dAoeXhWtlp9GQVoZaE?usp=drive_link"],
      ["Sort Key_1.", "Drive Video", "https://drive.google.com/drive/folders/1lCr6rlYY-MXk_Ypa029Atpjpg3GYvtT6?usp=drive_link"],
      ["Sort Key_2.", "Drive Video", "https://drive.google.com/drive/folders/1lCr6rlYY-MXk_Ypa029Atpjpg3GYvtT6?usp=drive_link"],
      ["Announcement of free enrollment.", "Drive Video", "https://drive.google.com/drive/folders/19FKVQ7PCZTIaTjO4gXzkk5DdhuvGUTVt?usp=drive_link"],
      ["Vendor Master (Detailed Explanation).", "Drive Video", "https://drive.google.com/drive/folders/1T_9MIwMqkOP9mPj4FUgjVAS-ElZz16cW?usp=drive_link"],
      ["Vendor Down Payment_1.", "Drive Video", "https://drive.google.com/drive/folders/1T_9MIwMqkOP9mPj4FUgjVAS-ElZz16cW?usp=drive_link"],
      ["Net-weaver_Decimal Digit.", "Drive Video", "https://drive.google.com/drive/folders/1pWzVdnmk7Jd_ivd5JSLLzbp24dxzBuOL?usp=drive_link"],
      ["Dunning_Testing.", "Drive Video", "https://drive.google.com/drive/folders/1pWzVdnmk7Jd_ivd5JSLLzbp24dxzBuOL?usp=drive_link"],
      ["Chart of Depreciation.", "Drive Video", "https://drive.google.com/drive/folders/1iCqZQf2E6csgv-bcbmMgGM7SoOjU8s2C?usp=drive_link"],
      ["Asset class.", "Drive Video", "https://drive.google.com/drive/folders/1iCqZQf2E6csgv-bcbmMgGM7SoOjU8s2C?usp=drive_link"],
      ["Account Determination", "Drive Video", "https://drive.google.com/drive/folders/1iCqZQf2E6csgv-bcbmMgGM7SoOjU8s2C?usp=drive_link"],
      ["Determination of Dep. Area.", "Drive Video", "https://drive.google.com/drive/folders/1iCqZQf2E6csgv-bcbmMgGM7SoOjU8s2C?usp=drive_link"],
      ["Depreciation Cal. Methods.", "Drive Video", "https://drive.google.com/drive/folders/1iCqZQf2E6csgv-bcbmMgGM7SoOjU8s2C?usp=drive_link"],
      ["Asset Master.", "Drive Video", "https://drive.google.com/drive/folders/1iCqZQf2E6csgv-bcbmMgGM7SoOjU8s2C?usp=drive_link"],
      ["Asset Depreciation.", "Drive Video", "https://drive.google.com/drive/folders/1iCqZQf2E6csgv-bcbmMgGM7SoOjU8s2C?usp=drive_link"],
      ["Financial Statement Version", "Drive Video", "https://drive.google.com/drive/folders/1YCxgIGb1D6Q52-WkX-34YrC9QyRqgW2E?usp=drive_link"],
      ["Message no. F5201", "Drive Video", "https://drive.google.com/drive/folders/1ZTu2Gw1-BX5led1EPCAXwvVgB273nc5i?usp=drive_link"],
      ["Message no. F5150.", "Drive Video", "https://drive.google.com/drive/folders/1ZTu2Gw1-BX5led1EPCAXwvVgB273nc5i?usp=drive_link"],
      ["Message no. GLT2076", "Drive Video", "https://drive.google.com/drive/folders/1ZTu2Gw1-BX5led1EPCAXwvVgB273nc5i?usp=drive_link"],
      ["Message no. F5562", "Drive Video", "https://drive.google.com/drive/folders/1ZTu2Gw1-BX5led1EPCAXwvVgB273nc5i?usp=drive_link"],
      ["Message no. ME062", "Drive Video", "https://drive.google.com/drive/folders/1ZTu2Gw1-BX5led1EPCAXwvVgB273nc5i?usp=drive_link"],
      ["Message no. F5286", "Drive Video", "https://drive.google.com/drive/folders/1ZTu2Gw1-BX5led1EPCAXwvVgB273nc5i?usp=drive_link"],
      ["Message no. F5103", "Drive Video", "https://drive.google.com/drive/folders/1ZTu2Gw1-BX5led1EPCAXwvVgB273nc5i?usp=drive_link"],
      ["Message no. F2007", "Drive Video", "https://drive.google.com/drive/folders/1ZTu2Gw1-BX5led1EPCAXwvVgB273nc5i?usp=drive_link"],
      ["Message no. GI102", "Drive Video", "https://drive.google.com/drive/folders/1ZTu2Gw1-BX5led1EPCAXwvVgB273nc5i?usp=drive_link"],
      ["Message no. F5011", "Drive Video", "https://drive.google.com/drive/folders/1ZTu2Gw1-BX5led1EPCAXwvVgB273nc5i?usp=drive_link"],
      ["Message no. F5010", "Drive Video", "https://drive.google.com/drive/folders/1ZTu2Gw1-BX5led1EPCAXwvVgB273nc5i?usp=drive_link"],
    ],
  },
};

const params = new URLSearchParams(window.location.search);
const selectedCourse = courses[params.get("course")] || courses["ms-basic"];
const warning = document.querySelector("[data-drive-warning]");
const openVideoLink = document.querySelector("[data-open-video]");

const getTotalDuration = (topics) => {
  const minutes = topics.reduce((total, [, length]) => total + Number(length.replace(/[^0-9]/g, "")), 0);
  if (!minutes) return "Private Videos";
  return `${minutes} min`;
};

const renderCourse = () => {
  document.title = `${selectedCourse.label} | Uncut_Lesson`;
  document.querySelector("[data-course-label]").textContent = selectedCourse.label;
  document.querySelector("[data-course-title]").textContent = selectedCourse.title;
  document.querySelector("[data-course-description]").textContent = selectedCourse.description;
  document.querySelector("[data-course-image]").src = selectedCourse.image;
  document.querySelector("[data-course-count]").textContent = `${selectedCourse.topics.length} Videos`;
  document.querySelector("[data-course-duration]").textContent = getTotalDuration(selectedCourse.topics);
  document.querySelector("[data-sidebar-title]").textContent = selectedCourse.label;
  document.querySelector("[data-sidebar-text]").textContent = `${selectedCourse.price} course. Video access works only after Drive approval.`;
  document.querySelector("[data-payment-link]").href = selectedCourse.payment;

  const list = document.querySelector("[data-topic-list]");
  list.innerHTML = selectedCourse.topics.map(([topic, length, videoUrl = drivePlaceholder], index) => `
    <article class="learning-topic-card">
      <div class="topic-number">${String(index + 1).padStart(2, "0")}</div>
      <div>
        <h2>${topic}</h2>
        <p>${length}</p>
      </div>
      <button type="button" data-watch-video data-video-url="${videoUrl}">Watch Video</button>
    </article>
  `).join("");
};

document.addEventListener("click", (event) => {
  const watchButton = event.target.closest("[data-watch-video]");
  if (!watchButton) return;

  const videoUrl = watchButton.dataset.videoUrl || drivePlaceholder;

  if (videoUrl === drivePlaceholder) {
    alert("Video link is not added yet. Add your private Google Drive video link in learning.js.");
    return;
  }

  openVideoLink.href = videoUrl;
  warning.hidden = false;
});

document.querySelector("[data-close-warning]").addEventListener("click", () => {
  warning.hidden = true;
});

warning.addEventListener("click", (event) => {
  if (event.target === warning) {
    warning.hidden = true;
  }
});

renderCourse();
